export const SEARCH_REPOSITORIES_REQUEST = 'SEARCH_REPOSITORIES_REQUEST';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_FAILURE = 'SEARCH_REPOSITORIES_FAILURE';